title: Alexander Brunkow
author: Alexander Brunkow
description: Immer ein aktueller Überblick über meine Qualifikationen und Projekte
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false

# Navigation (falls vom Theme unterstützt)
navigation:
  - title: Home
    url: /
  - title: Über mich
    url: /about
  - title: Projekte
    url: /projects
  - title: Kontakt
    url: /contact
