title: Alexander Brunkow Portfolio
author: Alexander Brunkow
description: IT-Security-Experte | Student |
theme: jekyll-theme-minimal
show_downloads: false

# Navigation (falls vom Theme unterstützt)
navigation:
  - title: Home
    url: /
  - title: Über mich
    url: /about
  - title: Projekte
    url: /projects
  - title: Kontakt
    url: /contact
